#security:
#  user:
#    name: root
#    password: root
#  basic:
#    enabled: true
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/